### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by LucidSamuel** [FreeLeh/PyFreeDB#3]
Hello, I think this is an amazing project and I would be willing to help improve the documentation and also create a landing page for PyFreeLeh

**Comment by dndplsidc** [comment]
Hi @LucidSamuel, thanks for your interest in this project!

Could you elaborate more what kind of documentation and landing page you have in mind? I think it's a good idea, but I feel we should align the idea too.

**Comment by LucidSamuel** [comment]
Oh yeah sure, I was thinking of a more dev-focused page (https://www.npmjs.com/) that would give insight to the page and the probably convert the readme page to a documentation page. 
That might be too much but I'd also like to see what you've got In mind.

**Comment by dndplsidc** [comment]
Oh I see. I think that's going to be useful. But to be honest with you, we may not be able to give a full attention to this in the very short term yet since we are still focusing on stabilising the main implementation.

However, we do foresee we will need something like a landing page + a more proper documentation (e.g. not sure about Python, but for the Golang version, we will be using a more common docs: godocs). In addition, we will be trying to summarise the main protocol in a language agnostic document that allows people to contribute implementations for other languages.

Anyways, we are totally open to kickstart this discussion right now, but we just want to let you know it's not on our top priority list **yet** (it will be soon). If you can give us a more concrete idea about the documentation and landing page structure, we will definitely check and discuss it with you from time to time. What do you think?
